name: ${project.name}
version: ${project.version}
description: Automatic inventory switching for groups of worlds
main: de.craftinc.inventories.Plugin
author: tomco, s1m0ne
authors: [drayshak, s1m0ne, tomco]

commands:
  wireload:
    description: Reload WorldInventories configuration
    permission: worldinventories.reload
    usage: /<command> [language/all]
  wiexempt:
    description: Manage exempt players
    permission: worldinventories.exempt
    usage: /<command> [add/remove] [player]

permissions:
  craftincinventories.*:
    description: Gives access to all Craft Inc. Inventories commands.
    children:
      craftincinventories.reload: true
      craftincinventories.exempt: true
    default: op
  craftincinventories.reload:
    description: Allows reloading of configurations and languages.
  craftincinventories.exempt:
    description: Allows adding and removing players to/from the exemption list.
