name: WorldInventories
main: me.drayshak.WorldInventories.WorldInventories
version: 1.7.0-dev4
author: drayshak
description: Automatic inventory switching for groups of worlds
commands:
  wireload:
    description: Reload WorldInventories configuration
    permission: worldinventories.reload
    usage: /<command> [language/all]
  wiexempt:
    description: Manage exempt players
    permission: worldinventories.exempt
    usage: /<command> [add/remove] [player]
permissions:
  worldinventories.*:
    children:
      worldinventories.reload: true
      worldinventories.exempt: true
    default: op